version: '3'
services:
  talk:
    build:
      context: .
      dockerfile: ./server/Dockerfile
      args:
        presentation: "${presentation}"
    ports:
      - "8000:8000"
    container_name: talk
